// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyANHsIkxz4kv1KeHLI__WA5l4isSRfcPzk',
    appId: '1:153266173349:web:d5135c259bdd3c7c13a44c',
    messagingSenderId: '153266173349',
    projectId: 'theftapp-40e59',
    authDomain: 'theftapp-40e59.firebaseapp.com',
    storageBucket: 'theftapp-40e59.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCTaXjC21DItDN0C89Z_p95s1agDuOjkh8',
    appId: '1:153266173349:android:80798e524f49469713a44c',
    messagingSenderId: '153266173349',
    projectId: 'theftapp-40e59',
    storageBucket: 'theftapp-40e59.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD4gE5wIrDdaQqU-ZmPHADrVc_QByOqnXA',
    appId: '1:153266173349:ios:31cb4ded37a4779f13a44c',
    messagingSenderId: '153266173349',
    projectId: 'theftapp-40e59',
    storageBucket: 'theftapp-40e59.firebasestorage.app',
    iosBundleId: 'com.example.theftApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD4gE5wIrDdaQqU-ZmPHADrVc_QByOqnXA',
    appId: '1:153266173349:ios:31cb4ded37a4779f13a44c',
    messagingSenderId: '153266173349',
    projectId: 'theftapp-40e59',
    storageBucket: 'theftapp-40e59.firebasestorage.app',
    iosBundleId: 'com.example.theftApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyANHsIkxz4kv1KeHLI__WA5l4isSRfcPzk',
    appId: '1:153266173349:web:1fb0aeeecaa6b38713a44c',
    messagingSenderId: '153266173349',
    projectId: 'theftapp-40e59',
    authDomain: 'theftapp-40e59.firebaseapp.com',
    storageBucket: 'theftapp-40e59.firebasestorage.app',
  );
}
